title: Angellina 

#logo: /assets/img/prajindra-removebg-preview-Photoroom.jpg

description: Bachelor of Computer Science (Cyber Security) (Honours)
#show_downloads: true

theme: jekyll-theme-minimal
